# Generated by Django 5.2 on 2025-04-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Номер договору')),
                ('contract_end_date', models.DateField(verbose_name='Дата закінчення договору')),
                ('students_count', models.PositiveIntegerField(verbose_name='Кількість студентів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Договір',
                'verbose_name_plural': 'Договори',
            },
        ),
        migrations.CreateModel(
            name='IngenerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Назва компанії')),
                ('code_edrpo', models.CharField(max_length=255, unique=True, verbose_name='Код ЄДРПОУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingener_info', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Інформація про інженера ОП',
                'verbose_name_plural': 'Інформація про інженерів ОП',
            },
        ),
        migrations.CreateModel(
            name='IngenerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingener_contracts', to='ingener_op_app.contract', verbose_name='Договір')),
                ('ingener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingener_contracts', to='ingener_op_app.ingenerinfo', verbose_name='Інженер')),
            ],
            options={
                'verbose_name': 'Договір інженера',
                'verbose_name_plural': 'Договори інженерів',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ingener_op_app.ingenerinfo', verbose_name='Клієнт'),
        ),
    ]
