# Generated by Django 5.2 on 2025-04-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='students_count',
        ),
    ]
