# Generated by Django 5.2 on 2025-04-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0002_remove_contract_students_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngenerContract',
        ),
    ]
