# Generated by Django 5.2 on 2025-04-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0004_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingener_op_app.ingenerinfo', verbose_name='Клієнт'),
        ),
    ]
