# Generated by Django 5.2 on 2025-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0005_alter_contract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingenerinfo',
            name='students_count',
            field=models.IntegerField(default=0, verbose_name='Кількість студентів'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер договору'),
        ),
    ]
