# Generated by Django 5.2 on 2025-05-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0006_ingenerinfo_students_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingenerinfo',
            name='students_count',
        ),
    ]
