# Generated by Django 5.1.7 on 2025-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingener_op_app", "0007_remove_ingenerinfo_students_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingenerinfo",
            name="is_new_registration",
            field=models.BooleanField(default=False, verbose_name="Новий користувач"),
        ),
    ]
