# Generated by Django 5.2 on 2025-04-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('ingener_op_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Інформація про студента ОП',
                'verbose_name_plural': 'Інформація про студентів ОП',
            },
        ),
        migrations.CreateModel(
            name='StudentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contracts', to='ingener_op_app.contract', verbose_name='Договір')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contracts', to='student_op_app.studentinfo', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Договір студента',
                'verbose_name_plural': 'Договори студентів',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Тривалість навчання')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('waiting_authorization', 'Очікує авторізації'), ('started', 'Розпочато'), ('completed', 'Завершено')], default='new', max_length=255, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='admin_app.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='student_op_app.studentinfo', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Навчання',
                'verbose_name_plural': 'Навчання',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_comlited', models.BooleanField(default=False, verbose_name='Чи пройдено')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='student_op_app.education', verbose_name='Навчання')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='student_op_app.studentinfo', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Тестування',
                'verbose_name_plural': 'Тестування',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Чи правильна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='admin_app.question', verbose_name='Питання')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='admin_app.answer', verbose_name='Вибрана відповідь')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='student_op_app.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Відповідь на тест',
                'verbose_name_plural': 'Відповіді на тест',
                'unique_together': {('test', 'question')},
            },
        ),
    ]
