# Generated by Django 5.2 on 2025-05-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('waiting_authorization', 'Очікує авторізації'), ('started', 'Розпочато'), ('completed', 'Завершено')], default='waiting_authorization', max_length=255, verbose_name='Статус'),
        ),
    ]
