# Generated by Django 5.2 on 2025-05-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0006_ingenerinfo_students_count_and_more'),
        ('student_op_app', '0002_alter_education_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_contracts', to='ingener_op_app.contract', verbose_name='Договір'),
        ),
    ]
