# Generated by Django 5.2 on 2025-05-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingener_op_app', '0006_ingenerinfo_students_count_and_more'),
        ('student_op_app', '0004_studentinfo_client_delete_studentcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='client',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ingener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='ingener_op_app.ingenerinfo', verbose_name='Компанія'),
            preserve_default=False,
        ),
    ]
