# Generated by Django 5.2 on 2025-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0006_answer_alter_studentanswer_selected_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Спроби'),
        ),
    ]
