# Generated by Django 5.2 on 2025-05-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_delete_answer_delete_question'),
        ('student_op_app', '0007_test_attempts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('student', 'course')},
        ),
    ]
