# Generated by Django 5.2 on 2025-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0008_alter_education_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='status',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.CharField(choices=[('waiting_authorization', 'Очікує авторізації'), ('started', 'Розпочато'), ('completed', 'Завершено')], default='waiting_authorization', max_length=255, verbose_name='Статус'),
        ),
    ]
