# Generated by Django 5.2 on 2025-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0009_remove_education_status_studentinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Тривалість навчання'),
        ),
    ]
