# Generated by Django 5.2 on 2025-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0010_studentinfo_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
    ]
