# Generated by Django 5.2 on 2025-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0011_remove_education_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Оцінка'),
        ),
    ]
