# Generated by Django 5.2 on 2025-05-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0012_education_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='score',
            new_name='last_score',
        ),
    ]
