# Generated by Django 5.1.7 on 2025-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_op_app", "0013_rename_score_education_last_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Час початку тесту"
            ),
        ),
    ]
