# Generated by Django 5.2 on 2025-06-01 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_op_app', '0015_remove_education_last_score_education_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to='student_op_app.studentinfo', verbose_name='Студент'),
        ),
    ]
