[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "./start.sh"

# Environment variables
[env]
# These will be set automatically by Railway
# DATABASE_URL - automatically set when PostgreSQL service is added
# PORT - automatically set by Railway
# RAILWAY_ENVIRONMENT - automatically set to "production"

[services.web]
# Dependencies - ensure PostgreSQL starts before web service
dependsOn = ["database"] 