# Generated by Django 5.2 on 2025-05-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
    ]
