# Generated by Django 5.2 on 2025-05-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
