# Generated by Django 5.2 on 2025-05-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_answer_question_and_more'),
        ('student_op_app', '0006_answer_alter_studentanswer_selected_answer_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
