# Generated by Django 5.2 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='№ курсу'),
        ),
    ]
